### ISSUE TITLE
vlc flatpak does not run in linuxmint 18.2

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.videolan.VLC#1]
hi, vlc flatpak is already install in linuxmint 18.2 but not run.
I use the flatpak commands to run and it does not work.

**Comment by TingPing** [comment]
Any error output?

**Comment by Lvaskz** [comment]
The application does not run, does not work

2017-09-18 16:08 GMT-06:00 TingPing <notifications@github.com>:

**Comment by legacychimera247** [comment]
i have fedora workstation 26 and seems the app only run if launched via terminal...

here's what the terminal says...maybe it's the same problem

`VLC media player 3.0.0-git Vetinari (revision 2.2.0-git-14263-g954ec0a4e9)
[0000000001660f00] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[00000000016e90b0] core playlist: playlist is empty
`

**Comment by Lvaskz** [comment]
Yes, the same problem. i will send a video later, but yes that is the
problem.

2017-09-19 3:01 GMT-06:00 legacychimera247 <notifications@github.com>:

**Comment by adityashah1212** [comment]
I am also facing the same problem as @legacychimera247 on fedora 26, I don't know how to get a log but if someone can point me in the right direction get the details needed.

**Comment by cosimoc** [comment]
Looks like something ends up appending wrong parameters to the desktop file when it gets exported... Will look into that.

**Comment by cosimoc** [comment]
Pushed a fix to master that is now building.

**Comment by cosimoc** [comment]
Seems to be building OK and the fix should be hitting the repos soon. Please report if it did not work!
