### ISSUE TITLE
live555 source doesn't exist anymore

### ISSUE THREAD

**Issue by hadess** [flathub/org.videolan.VLC#100]
http://www.live555.com/liveMedia/public/live.2019.12.13.tar.gz is gone.

http://www.live555.com/liveMedia/public/live.2020.03.06.tar.gz is the latest version (sha256sum is `35c0aedc6cfb91d7204a343f6944cc7ab327e0f473ad6ce3d22bc5195f86a96c`)

**Comment by MatMaul** [comment]
Hum I need to find a mirror which keeps old builds unlike the official ones :/ closing for now, it is working again.
