### ISSUE TITLE
Can org.videolan.VLC be launched as a native wayland application ?

### ISSUE THREAD

**Issue by antistress** [flathub/org.videolan.VLC#102]
Hi,

I've just checked on my Debian Testing GNOME-Wayland system with $ xlsclients and org.videolan.VLC is running through XWayland.

Can org.videolan.VLC be used without XWayland (for instance using --socket=wayland or any other setting), as a native wayland application, or shall we wait for version 4 ?

Here is what I found :
https://wiki.videolan.org/WaylandIntegration/
https://www.phoronix.com/scan.php?page=news_item&px=VLC-2019-Feature-Talk

Thanks !

**Comment by MatMaul** [comment]
Indeed Wayland support is not complete at all on v3 and should be in good shape for v4.
