### ISSUE TITLE
VLC can't start or open files

### ISSUE THREAD

**Issue by siroccal** [flathub/org.videolan.VLC#107]
VLC doesn't start and can't open any files. I inspected the desktop entry file and found it contained `--started-from-file`. After removing that, VLC works fine.

Workaround:
`sed "s/--started-from-file//g" -i $HOME/.local/share/flatpak/exports/share/applications/org.videolan.VLC.desktop`

**Comment by Erick555** [comment]
It works for me without changes

**Comment by MatMaul** [comment]
It also works perfectly fine for me, closing.
