### ISSUE TITLE
[Question] Does this flatpak can access & install add-on from add-on page or just from FlatHUb

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.videolan.VLC#109]
Hi. I would like to know: does this flatpak able to install add-on directly from official add-on page of VLC or it can only do from FlatHub available VLC plugins ??

**Comment by MatMaul** [comment]
Yes you can go in the menu `Tools -> Plugins and extensions` to install them directly.

**Comment by MatMaul** [comment]
Extensions only, not the plugins. Plugins would need extra work.
