### ISSUE TITLE
VLC recognizes java but doesn't load it.

### ISSUE THREAD

**Issue by asheimo** [flathub/org.videolan.VLC#114]
I am trying to load a 4k disc and have java installed. VLC recognizes java is installed but does not load it so I don't see the menus its just black. Not sure what I may be missing. I have the JAVA_HOME and JRE_PATH variables set.

![image](https://user-images.githubusercontent.com/33631251/93494434-072ae780-f8db-11ea-981f-9040a18e90fa.png)

**Comment by MatMaul** [comment]
You need to have org.videolan.VLC.Plugin.bdj installed to have Java based menus.
