### ISSUE TITLE
Update the runtime to Kde 5.15

### ISSUE THREAD

**Issue by codingepaduli** [flathub/org.videolan.VLC#115]
Please, update the runtime to org.kde.Platform/x86_64/5.15
Thanks

**Comment by Erick555** [comment]
See https://github.com/flathub/org.videolan.VLC/pull/113

**Comment by Erick555** [comment]
This is fixed now but all plugins need branches for 20.08 in order to work.

**Comment by MatMaul** [comment]
All done now.
