### ISSUE TITLE
Indicator icon is incorrect

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.videolan.VLC#117]
After enabling indicator icon support (eg with `flatpak override --user --own-name=org.kde.* --talk-name=org.kde.StatusNotifierWatcher org.videolan.VLC`), the icon is now incorrect (it used to be correct and the deb version is still correct).

I expected the indicator icon to be the VLC logo.

![image](https://user-images.githubusercontent.com/3669750/96768942-58e0f900-13d6-11eb-928e-31e4c7779174.png)

**Comment by MatMaul** [comment]
I don't have this problem (I am also on Gnome), please reopen with more infos (like logs when doing `flatpak run`) if it is still the case.
