### ISSUE TITLE
RTSP not working after 3.0.12 Update

### ISSUE THREAD

**Issue by BOFH90** [flathub/org.videolan.VLC#121]
RTSP Stream (H264) works directly before the Update on 3 devices i tested and stopped after it:

main debug: processing request item: rtsp://10.0.6.116:554/Streaming/Channels/101, node: Wiedergabeliste, skip: 0
main debug: rebuilding array of current - root Wiedergabeliste
main debug: rebuild done - 2 items, index 1
main debug: starting playback of new item
main debug: resyncing on rtsp://10.0.6.116:554/Streaming/Channels/101
main debug: rtsp://10.0.6.116:554/Streaming/Channels/101 is at 1
main debug: creating new input thread
main debug: Creating an input for 'rtsp://10.0.6.116:554/Streaming/Channels/101'
main debug: requesting art for new input thread
main debug: using timeshift granularity of 50 MiB
main debug: using default timeshift path
main debug: `rtsp://10.0.6.116:554/Streaming/Channels/101' gives access `rtsp' demux `any' path `10.0.6.116:554/Streaming/Channels/101'
main debug: creating demux: access='rtsp' demux='any' location='10.0.6.116:554/Streaming/Channels/101' file='(null)'
main debug: looking for access_demux module matching "rtsp": 18 candidates
main debug: no access_demux modules matched
main debug: creating access: rtsp://10.0.6.116:554/Streaming/Channels/101
main debug: looking for access module matching "rtsp": 29 candidates
satip debug: try to open 'rtsp://10.0.6.116:554/Streaming/Channels/101'
main debug: looking for meta fetcher module matching "any": 1 candidates
satip debug: connect to host '10.0.6.116'
main debug: net: connecting to 10.0.6.116 port 554
lua debug: Trying Lua scripts in /home/michael/.var/app/org.videolan.VLC/data/vlc/lua/meta/fetcher
lua debug: Trying Lua scripts in /app/lib/vlc/lua/meta/fetcher
lua debug: Trying Lua scripts in /app/share/vlc/lua/meta/fetcher
main debug: no meta fetcher modules matched
main debug: looking for art finder module matching "any": 2 candidates
lua debug: Trying Lua scripts in /home/michael/.var/app/org.videolan.VLC/data/vlc/lua/meta/art
lua debug: Trying Lua scripts in /app/lib/vlc/lua/meta/art
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/00_musicbrainz.luac
lua debug: skipping script (unmatched scope) /app/lib/vlc/lua/meta/art/00_musicbrainz.luac
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/01_googleimage.luac
main debug: connection succeeded (socket = 23)
main debug: net: opening 0.0.0.0 datagram port 9282
main debug: net: opening 0.0.0.0 datagram port 9283
lua debug: skipping script (unmatched scope) /app/lib/vlc/lua/meta/art/01_googleimage.luac
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/02_frenchtv.luac
lua debug: skipping script (unmatched scope) /app/lib/vlc/lua/meta/art/02_frenchtv.luac
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/03_lastfm.luac
lua debug: skipping script (unmatched scope) /app/lib/vlc/lua/meta/art/03_lastfm.luac
lua debug: Trying Lua scripts in /app/share/vlc/lua/meta/art
main debug: no art finder modules matched
main debug: looking for meta fetcher module matching "any": 1 candidates
lua debug: Trying Lua scripts in /home/michael/.var/app/org.videolan.VLC/data/vlc/lua/meta/fetcher
lua debug: Trying Lua scripts in /app/lib/vlc/lua/meta/fetcher
lua debug: Trying Lua scripts in /app/share/vlc/lua/meta/fetcher
main debug: no meta fetcher modules matched
main debug: looking for art finder module matching "any": 2 candidates
lua debug: Trying Lua scripts in /home/michael/.var/app/org.videolan.VLC/data/vlc/lua/meta/art
lua debug: Trying Lua scripts in /app/lib/vlc/lua/meta/art
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/00_musicbrainz.luac
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/01_googleimage.luac
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/02_frenchtv.luac
lua debug: Trying Lua playlist script /app/lib/vlc/lua/meta/art/03_lastfm.luac
lua debug: Trying Lua scripts in /app/share/vlc/lua/meta/art
main debug: no art finder modules matched
qt debug: IM: Setting an input
satip error: Failed to setup RTSP session
main debug: no access modules matched
main debug: dead input
qt debug: IM: Deleting the input
main debug: changing item without a request (current 1/2)
main debug: nothing to play

**Comment by Vulgaris-Viridis** [comment]
I can confirm, latest update breaks streaming functionality.

**Comment by MatMaul** [comment]
:/ thx for reporting.
This dependency (live555) is a nightmare, there is no versioning, and the official website only keeps the last archive with a date...
Going to try hunting the previous version we used here on a mirror.

**Comment by MatMaul** [comment]
Found, on VLC mirror :)
Should be out in a couple of hours, untested so please let me know.

**Comment by Vulgaris-Viridis** [comment]
That fixed it. Thanks, much appreciated!

**Comment by BOFH90** [comment]
Yes, its fixed now. Thank you :)
