### ISSUE TITLE
Pinning support issues on Linux Mint 20.1 Cinnamon

### ISSUE THREAD

**Issue by rvalenta4** [flathub/org.videolan.VLC#123]
As the title suggests, VLC version 3.0.12 updated on February 19, 2021 does not get correcly pinned to taskbar in Linux Mint 20.1 Cinnamon. Upon clicking on the pinned icon, VLC opens and shows the following error

Playback failure:
DVDRead could not open the disc "/dev/sr0".
Your input can't be opened:
VLC is unable to open the MRL 'dvd://'. Check the log for details.

After closing the message, the player works as expected, but it is still a minor annoyance.

The issue was reproducible on multiple Linux Mint 20.1 computers I have, including an old Laptop with a DVD drive and a fairly recent build with the following specs:

Intel i5-9600k
Gigabyte Z390 UD
Samsung 970 EVO m.2 
no DVD drive

The application works fine when opened from the menu.

**Comment by MatMaul** [comment]
@rvalenta4 Is it possible that you pinned it after opening a DVD ? Does it also happen if you pin directly from the menubar if possible, or after opening it from there ?
