### ISSUE TITLE
disable video can be cause problem in other software?

### ISSUE THREAD

**Issue by saulo1131** [flathub/org.videolan.VLC#130]
I disabled video of VLC Player to listen to some musics of Youtube. Later I did join at an conference with 19 participants, but just me can not viewed the presentation shared for the speaker. I did try to reinstall the Teams, but the issue did still, then I clean the directory "home/.var/app/com.microsoft.Teams" and do reinstall again. Looks like it worked when I did test with two devices but I going to confirm if really work at next conference. It is possible that the issue can be caused for disble video on VCL ?

**Comment by MatMaul** [comment]
No, this should have nothing to do with VLC, sorry.
