### ISSUE TITLE
VLC won't connect to chromecast

### ISSUE THREAD

**Issue by chaibronz** [flathub/org.videolan.VLC#138]
Hello,

I'm not sure if this is a Flatpak security issue (or feature), but I'm not able to connect to my chromecast when using the Flatpak version of VLC. If I use my distro's repo version of VLC it works, but with Flatpak, I get the following error:

'main stream output error: stream chain failed for `chromecast{ip=xxx.xxx.x.xx,port=8009}’

I suspect this has something to do with Flatpak restricting access to the specific port chromecast uses (8009), but hoping there is a way to resolve or enable access somehow.

**Comment by tinywrkb** [comment]
@chaibronz please try the 2nd test build (75011), and if it doesn't work then try the 1st one (75002).

**Comment by chaibronz** [comment]
@tinywrkb   thanks so much, I tried build 75011 and it's working!  I do get the below error message now, but VLC seems to ignore it and stream anyway so doesn't seem significant  : )

**VLC now streams to chromecast with the following error message**
"[00007fe779196880] gnutls tls client error: Certificate verification failure: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected. 
[00007fe779196880] gnutls tls client: Accepting self-signed/untrusted CA certificate.
[00007fe7795ee9c0] main decoder error: cannot continue streaming due to errors with codec ssa "

**Comment by tinywrkb** [comment]
The certificate error seems to be a known issue. It doesn't look like there's something to do here from Flatpak packaging side.

I'm not sure about the SSA error. I suspect that subtitles are broken.  
Anyway, I'll go ahead and remove the draft from the CI, so it could be merged.  
If you notice an issue with displaying subtitles from the stream on the Chromecast, then please open another bug report.

**Comment by tinywrkb** [comment]
And thanks for testing!
