### ISSUE TITLE
Qt: Session management error

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.videolan.VLC#14]
VLC media player 3.0.0-git Vetinari (revision 2.2.0-git-14263-g954ec0a4e9)
[0000000001524f00] core libvlc: Executando o VLC com a interface padrão. Use 'cvlc' para usar o VLC sem interface.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[00000000015b18f0] core playlist: playlist is empty
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by MatMaul** [comment]
Closing, please reopen with more infos like the used distribution if still happening.
