### ISSUE TITLE
VLC Flat | Error | Video Conten Displaced GUI 

### ISSUE THREAD

**Issue by karolus-pt** [flathub/org.videolan.VLC#146]
Error: video content is displaced from the GUI (both when VLC is started from the command line and when the icon is fixed on the program bar. See image of the problem (Cf. https://ibb.co/vJtXdSw). 
![Screenshot from 2022-07-27 14-16-28](https://user-images.githubusercontent.com/110121985/181310324-54c8e061-b60a-4609-aade-e832716757ee.png)

**Comment by karolus-pt** [comment]
P.S. **Error similar to the one reported in**: vlc takes a while to start videos and then open it in a second window. #140 ⬅️

**Comment by MatMaul** [comment]
It seems related to a bug that should now be fixed in freedesktop SDK (cf #140), so closing, please reopen if you still have the trouble.
