### ISSUE TITLE
Wayland with mixed DPI monitor setup not working correctly for vlc

### ISSUE THREAD

**Issue by hzulla** [flathub/org.videolan.VLC#147]
Please see https://github.com/flatpak/flatpak/issues/5033 for details.

If you run the flatpak version of VLC on Ubuntu/Wayland and have two monitors attached with different scaling, the VLC UI will not change its scaling when moved from the hidpi monitor to the lodpi monitor and back.

The workaround --nosocket=fallback-x11 --nosocket=x11 --socket=wayland mentioned on https://github.com/flatpak/flatpak/issues/5033 works for Wayland-aware applications like Firefox, but not for flatpak VLC.

I do not know if this is a generic flatpak issue or if it is a packaging problem.

**Comment by orowith2os** [comment]
I think this is a general VLC issue, DPI scaling shouldnt be affected by flatpak.

**Comment by MatMaul** [comment]
Yes I think it is not specific to Flatpak VLC so closing.
