### ISSUE TITLE
Videos just play sound and show black image

### ISSUE THREAD

**Issue by andreldmonteiro** [flathub/org.videolan.VLC#152]
Videos on the flatpak version of VLC from flathub just play sound and show a black image, the VLC from the distro works fine, this bug is likely attributed to the old runtime used as can be seen by the errors, please update to 22.08.

$ flatpak run org.videolan.VLC '/run/media/user/movie.mkv' 
VLC media player 3.0.18 Vetinari (revision 3.0.18-0-ge9eceae)
[00005570eee8d0e0] main libvlc: VLC em execução com a interface predefinida. Utilize 'cvlc' para utilizar o VLC sem interface.
Gtk-Message: 22:32:00.269: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:32:00.269: Failed to load module "pk-gtk-module"
Gtk-Message: 22:32:00.269: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:32:00.269: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
amdgpu: unknown (family_id, chip_external_rev): (149, 2)
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
amdgpu: unknown (family_id, chip_external_rev): (149, 2)
libEGL warning: DRI2: failed to create dri screen
amdgpu: unknown (family_id, chip_external_rev): (149, 2)
libEGL warning: DRI2: failed to create dri screen

**Comment by MatMaul** [comment]
Ok I was waiting to see if I should push a new runtime with version 4 of VLC but if people began having trouble because of this I'll probably just update. Thanks for the report.

**Comment by MatMaul** [comment]
@andreldmonteiro can you try the test build available here ?
https://github.com/flathub/org.videolan.VLC/pull/153

**Comment by andreldmonteiro** [comment]
Many thanks, the new version not only fixed the video issue but also fixed the HDR problem on videos that I was having!
