### ISSUE TITLE
VLC is not in Flathub

### ISSUE THREAD

**Issue by ashuradji** [flathub/org.videolan.VLC#164]
The provided link does not work (Flathub 404) and searching for "VLC" in flathub does not show the app

**Comment by Rimmons** [comment]
I've just tried installing via that konsole command, this is the error message I received:

"No remote refs found similar to ?org.videolan.VLC?"

Searching directly on the Flathub site also leads to a 404 page.

**Comment by cyberfrogg** [comment]
Flathub.org says 404 on website. So it can be related. (url: https://flathub.org/ru/apps/org.videolan.VLC).
I tried to install it rn and it works fine: `flatpak --user install org.videolan.VLC`. 

- Fedora Linux 38.20230610.0 (Silverblue) 38 
- GNOME 44.2

Also *possibly?* you could miss flathub repo (https://flatpak.org/setup/)

**Comment by sebastiaanfranken** [comment]
> > You can still install via `flatpak install org.videolan.VLC`
> 
> I've just tried installing via that konsole command, this is the error message I received:
> 
> "No remote refs found similar to ?org.videolan.VLC?"
> 
> Searching directly on the Flathub site also leads to a 404 page.

And what does `flatpak install flathub org.videolan.VLC` do? For me (Fedora 38), that works and installs VLC

**Comment by Rimmons** [comment]
> And what does flatpak install flathub org.videolan.VLC do? For me (Fedora 38), that works and installs VLC

This command worked! Finally got VLC on my Steam Deck after fruitless attempts all weekend haha.

**Comment by MatMaul** [comment]
it was a trouble with an upgrade on flathub software itself, it's back now.
