### ISSUE TITLE
Missing AACS configuration file!

### ISSUE THREAD

**Issue by orvitpng** [flathub/org.videolan.VLC#170]
Using flatseal, I applied the override that gave VLC `xdg-config/aacs:ro`, and the file is there. It works well when I'm not using the flatpak. I don't know what my next steps should be.

**Comment by mbugni** [comment]
Hi,
this works for me:
```shell
$ flatpak override --user --filesystem=xdg-config/aacs:ro org.videolan.VLC
```

**Comment by orvitpng** [comment]
I can confirm that fixes my issue. Seems like maybe a problem with Flatseal
