### ISSUE TITLE
Doesn't open network stream of Youtube videos

### ISSUE THREAD

**Issue by niamotullah** [flathub/org.videolan.VLC#183]
Playing Youtube video from youtube-url working in **Snap** version of VLC, aren't working in **Flatpak** version of VLC.

**Edit:**
Seems it **has been fixed in release of `3.0.19`** , and **Flatpak** version of VLC still **hasn't been updated yet to `3.0.19`**

![275250198-1e626bae-e105-40a6-8f69-4be0a18443c6](https://github.com/flathub/org.videolan.VLC/assets/58494481/7e3b57c5-88e7-4402-8af5-ac00df5c3bb3)

**Comment by niamotullah** [comment]
> Playing Youtube video from youtube-url working in Snap version of VLC, aren't working in Flatpak version of VLC.
> 
> ![Screenshot from 2023-10-14 22-05-04](https://user-images.githubusercontent.com/58494481/275249894-2f3878f5-d259-4bde-b28f-59247168b457.png)

Seems it has been fixed on version 3.0.19.
![Screenshot from 2023-10-14 22-08-19](https://github.com/flathub/org.videolan.VLC/assets/58494481/1e626bae-e105-40a6-8f69-4be0a18443c6)

**Comment by MatMaul** [comment]
Version 3.0.19 has been deployed, I am closing but feel free to reopen if you still have the trouble.
