### ISSUE TITLE
Media->Convert Runaway Code

### ISSUE THREAD

**Issue by AlexanderAdelAU** [flathub/org.videolan.VLC#186]
If you convert an mkv file to mp4 using Media->convert.  The conversion is successful but then VLC pops up a dialogue with 

`"The output file already exists.  If recording continues, the file will be overridden and its content will be lost"`

Once in this state non of the buttons will close the dialogue and it appears the application is hung or the code is in runaway.

The only way to terminate is to end the task.

Running VLC 3.19 under Windows 11

**Comment by Erick555** [comment]
This repo is Linux only (flatpak). You need to report it elsewhere.

**Comment by AlexanderAdelAU** [comment]
Wrong platform
