### ISSUE TITLE
Update to version 3.0

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.videolan.VLC#19]
Apparently VLC 3.0 has been released (or will be soon). I think having it in Flathub near the release time will encourage a lot of users to try flatpak/flathub

https://www.phoronix.com/scan.php?page=news_item&px=VLC-3.0-Released

**Comment by nedrichards** [comment]
It has been released just now: https://www.videolan.org/vlc/releases/3.0.0.html

**Comment by nedrichards** [comment]
We probably want to merge https://github.com/flathub/org.videolan.VLC/pull/15 first

**Comment by MatMaul** [comment]
Yes it includes some required stuffs for a nominal 3.0 release like libplacebo.

**Comment by Lvaskz** [comment]
![ksnip_20180211](https://user-images.githubusercontent.com/29207169/36079117-3107dfb8-0f45-11e8-9be6-d6d1daceb63e.png)

when it will be release?

**Comment by jgarciao** [comment]
Thank you, it works very well with all the videos I've tested (h264+mkv and MPEG-4+avi)
