### ISSUE TITLE
Use KDE Sdk

### ISSUE THREAD

**Issue by MatMaul** [flathub/org.videolan.VLC#2]
I have done kind of the same work here:
https://github.com/kinvolk/vlc-flatpak/pull/19
I'll open some bugs/PR for the differences that I find useful.

First one, any reason to not use the KDE Sdk as a base ?
If you agree with the principle I can do a PR.

**Comment by cosimoc** [comment]
@MatMaul The main reason was that the KDE Sdk was not available on Flathub. If it's available and stable now, I'd be very happy to switch VLC to it, if it simplifies the manifest.

**Comment by MatMaul** [comment]
It is working quite well on my side.
The only problem is that we loose this patch:
https://github.com/flathub/shared-modules/blob/master/qt5/qtbase-hidpi_scale_at_192.patch
I am affected by the problem actually, I have a XPS 13 with a DPI detected as HiDPI while it's not.
I export QT_AUTO_SCREEN_SCALE_FACTOR=0 globally in my bashrc to fix it so I am unsure what to do here, should we keep patched Qt or let the user discovers QT_AUTO_SCREEN_SCALE_FACTOR until it is fixed upstream ?

**Comment by TingPing** [comment]
Maybe ask the KDE runtime maintainer if they will carry the patch?

**Comment by cosimoc** [comment]
@MatMaul It would not be acceptable to lose that patch; proper HiDpi support is the whole reason I updated this bundle to use the 3.0 snapshot in the first place. I don't think that asking users to set that environment variable is acceptable either -- it should just work.

I'd be happy to switch once that is fixed in the KDE runtime, or even bundling a patched QT5 on top of that if it still makes sense to switch.

**Comment by MatMaul** [comment]
Oh good idea I just checked and the patch is on an independant xcb module, it should be doable to only build that, or at least to only install this one, I'll have a look.

**Comment by MatMaul** [comment]
@TingPing I am not sure the KDE flatpak maintainer will agree to include a patch against Qt but I can ask. Also I need to check the status of the upstream Qt bugs regarding that, I have them somewhere.

**Comment by TingPing** [comment]
On a somewhat related note do you know if all Qt5 applications have to pass `--env=QT_QPA_PLATFORM=flatpak`?

**Comment by eszlari** [comment]
> @MatMaul It would not be acceptable to lose that patch; proper HiDpi support is the whole reason I updated this bundle to use the 3.0 snapshot in the first place. I don't think that asking users to set that environment variable is acceptable either -- it should just work.

Well, at least for me this patch does not work (Dell P2715Q, 3840x2160). I get proper scaling only by setting QT_AUTO_SCREEN_SCALE_FACTOR to "1". But then it works for both, host apps and flatpaks that are build against the KDE runtime like Subsurface.

**Comment by eszlari** [comment]
Actually, forget what I wrote in my previous comment.

If you running KDE as a desktop, two variables get set:

* QT_AUTO_SCREEN_SCALE_FACTOR=0
* QT_SCREEN_SCALE_FACTORS=screen1=1.0;screen2=1.2 ...
(you can set QT_SCREEN_SCALE_FACTORS=2.0 for all screens)

Gnome bug: https://bugzilla.gnome.org/show_bug.cgi?id=791671
Qt bug: https://bugreports.qt.io/browse/QTBUG-65424

**Comment by TingPing** [comment]
Maybe @grulja or @aleixpol have input on the patch?

**Comment by aleixpol** [comment]
At the moment we aren't patching unless it's been accepted for a newer Qt version. I don't think we want to change the behaviour of applications between Flatpak and non-Flatpak.

Wouldn't passing `--env=QT_AUTO_SCREEN_SCALE_FACTOR=1` in `finish-args` do the trick?

**Comment by TingPing** [comment]
@aleixpol The patch doesn't hardcode 1, it just changes rounding behavior but it will scale to 2 still.

**Comment by aleixpol** [comment]
QT_AUTO_SCREEN_SCALE_FACTOR is so that it does the right thing™️, which in hindsight it's probably what this patch is trying to figure out.
Either way I don't see why flatpak would need a different, specific behaviour.

**Comment by TingPing** [comment]
> Either way I don't see why flatpak would need a different, specific behaviour.

It really isn't Flatpak specific, I imagine @cosimoc just wants this for Endless.

Could it at all be possible for this logic to exist in the GNOME platform for Qt? Since this behavior matches GNOMEs scaling.

**Comment by cosimoc** [comment]
Yeah, it isn't flatpak specific. As far as I understand HiDpi scaling is broken for any QT-based application running under GNOME due to the bug linked above, unless that patch is applied, because of how QT calculates the threshold to apply scaling.
FWIW the patch is already shipped by default at least in Fedora, which is where I took it from: https://src.fedoraproject.org/cgit/rpms/qt5-qtbase.git/tree/qt5-qtbase.spec#n89.

**Comment by eszlari** [comment]
@cosimoc I just tested this on the latest Fedora 28 Rawhide, and no, Qt apps are not scaled when I set scaling to 200%. Only setting QT_SCREEN_SCALE_FACTORS helped in my case.

**Comment by cosimoc** [comment]
@eszlari Sounds like a bug to be reported to Fedora? VLC from flathub is scaled correctly on my HiDpi machine.

**Comment by eszlari** [comment]
@cosimoc It's the same on Ubuntu 18.04 - but I noticed something interesting, while testing this: the VLC version (3.0.0~rc4-1ubuntu1) that they are shipping right now actually scales properly on my display out of the box, while other Qt based apps in Ubuntu 18.04 do not (I tested: kate, qtcreator, lyx). I found one other app that scaled properly (qbittorrent). So maybe it's a app specific problem and updating the flatpak to a newer version of VLC would fix this without the patch?

**Comment by aleixpol** [comment]
Has anyone submitted the patch through Qt's gerrit?
https://codereview.qt-project.org

**Comment by MatMaul** [comment]
@aleixpol I commented on some related bugs (including one with a complex patch to handle HiDPI scaling behavior) but nothing moved. Perhaps you can help me with that, here are the related bugs:
https://bugreports.qt.io/browse/QTBUG-53022
https://bugreports.qt.io/browse/QTBUG-55654

If you think submitting the simpler patch that we carry could help I can do it.

**Comment by aleixpol** [comment]
Hi @MatMaul, thanks for the work!
Most interesting would be to submit the patch through gerrit and specify the bug report that it fixes.
http://wiki.qt.io/Qt_Contribution_Guidelines

I don't have approval rights but I can help you get in touch with those who do.
HTH

**Comment by MatMaul** [comment]
@aleixpol here it is : 
https://codereview.qt-project.org/#/c/222052/

**Comment by MatMaul** [comment]
Merged :) :) 
@aleixpol should we patch Qt 5.9 LTS with it in flathub ?
I'll update VLC on Qt 5.11 as soon as it is released.

**Comment by aleixpol** [comment]
Hi,
I just tested, the patch doesn't apply against Qt 5.9. I could apply it against Qt 5.10 if you like.

**Comment by MatMaul** [comment]
As you want, honestly we can wait for 5.11 then, it's a month away. It was mainly because 5.9 is a LTS release and this stuff is painful, but I guess some user testing on 5.11 before the next LTS is not bad either :)

**Comment by aleixpol** [comment]
Okay, then we can wait. It was so that you could move on with this ticket.

**Comment by Alexander-Wilms** [comment]
Since KDE Sdk 5.11 has now been released, can you use it in the VLC manifest?

**Comment by MatMaul** [comment]
I tried, my patch didn't make it for the 5.11.0 release, however it is in 5.11 branch so we either wait for 5.11.1 or @aleixpol can perhaps add this commit to the flatpak runtime until then.
http://code.qt.io/cgit/qt/qtbase.git/commit/?id=23b139038a1dc9a769a358ab112453abcdd39290
