### ISSUE TITLE
VLC fails to validate root certificates for HTTPS network streams

### ISSUE THREAD

**Issue by da2x** [flathub/org.videolan.VLC#20]
Steps to reproduce:

1. Open VLC
2. Go to Media: Open Network Stream …
3. Type in any HTTPS media file from any certificate issuer (example https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5f/DollyZoomTest.ogv/DollyZoomTest.ogv.480p.webm)
4.  Click Play

Expected:

Should be able to validate against known root certificates in the Flatpak runtime.

Actual:

VLC doesn’t know about any root certificates so the user has to manually accept the certificate each time they want to play a network stream.

Notes:

The GlobalSign root used in the above example are included in at least org.freedesktop.Platform/x86_64/1.6, org.freedesktop.Platform.Compat32/x86_64/1.6, org.freedesktop.Sdk/x86_64/1.6, and org.gnome.Platform/x86_64/3.26.

**Comment by nedrichards** [comment]
Error message is:

> [00007f16f40020f0] gnutls tls client error: cannot load trusted Certificate Authorities from system: An unimplemented or disabled feature has been requested.

**Comment by da2x** [comment]
I just noticed a secondary issue: Neither of the override options `Accept permanently` nor `Accept 24 hours` are persistent for the given time ranges. If you set a video to look after accepting its certificate for 24 hours, VLC will still ask you to accept the certificate again even on the second play-through in the same session.

**Comment by MatMaul** [comment]
The secondary issue will be fixed by #27, this was because VLC needs write access to ~/.gnutls folder for the accept permanently to work.
However I can't reproduce your first problem, the link you gave works fine for me.

**Comment by da2x** [comment]
I also can’t reproduce the issue anymore. It affected every certificate, and not just the one in the example. However, it appears to work fine now.
