### ISSUE TITLE
VLC immediately throws up DVD read errors after creating a shortcut to the panel on Linux Mint ...

### ISSUE THREAD

**Issue by Omnimaxus** [flathub/org.videolan.VLC#202]
The Flatpak version of VLC puts up a DVD read error when I create a shortcut to the panel (taskbar) from the icon that shows up in the panel after VLC starts running.  **But the weird thing is when I start VLC from the menu itself, it works fine.** No DVD read errors. And when I hover over the shortcut in the panel, it says, "VLC media player (DVD)" for some reason. Not "VLC media player." I'm using the system package for VLC from the software center for now until the Flatpak version gets fixed.  Thanks.

(Side note: I'm using Linux Mint 21.3 Cinnamon [Edge] version.)

(One more thing - you can see pictures at this link - [CLICK HERE](https://forums.linuxmint.com/viewtopic.php?p=2429075#p2429075).)

**Comment by MatMaul** [comment]
I can reproduce and it is an issue with Cinnamon, I've opened a bug reporte [here](https://github.com/linuxmint/cinnamon/issues/12194).

**Comment by MatMaul** [comment]
Oh and in the meantime, if you `pin to panel` from the applications menu before opening instead of the taskbar after opening VLC, it all works fine.

**Comment by Omnimaxus** [comment]
Thank you very much.
