### ISSUE TITLE
Fix missing icon and category in appstream

### ISSUE THREAD

**Issue by rshuler** [flathub/org.videolan.VLC#21]
There was a regression in the past few days, and the appstream.xml no longer specifies an icon and category, and thus the app no longer shows up in gnome-software.

**Comment by TingPing** [comment]
The missing icon was a `flatpak` bug which was just fixed in the new release today, once those hit the builders it can be rebuilt and that will be fixed. This probably is the same for the categories.

**Comment by nedrichards** [comment]
I think we need to patch this - the builders don't get updated that quickly everywhere - or at least that was the latest info from @ramcq 

I'll spin up a PR.

**Comment by nedrichards** [comment]
https://github.com/flathub/org.videolan.VLC/pull/22

**Comment by TingPing** [comment]
@nedrichards Well that sucks, since in a week from now we'll just need to go around reverting this mess anyway.

**Comment by nedrichards** [comment]
It does suck. I'm going to check the situation first thing tomorrow and only push if gloomy.

**Comment by nedrichards** [comment]
Test build didn't fix the issue - so merged PR. Should be fixed by https://github.com/flathub/org.videolan.VLC/commit/0907f7cfa9fd6aa3cfc584e6deb72310631d632a when built
