### ISSUE TITLE
VLC flatpak wont launch from desktop shortcurt

### ISSUE THREAD

**Issue by Tractor777** [flathub/org.videolan.VLC#226]
### Description
VLC installed from flathub as a flatpak. VLC will not launch from the Gnome shortcut icon that is created. It will launch from the terminal using flatpak run org.videolan.VLC. The desktop shortcut contains the option "--started-from-file" (shown below) and if that option is removed VLC launches from the shortcut.

/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/vlc --file-forwarding org.videolan.VLC --started-from-file @@u %U @@

### Steps to Reproduce
flatpak install flathub org.videolan.VLC
Try and launch VLC from launcher icon
nothing happens

### Expected behavior
Try and launch VLC from launcher icon
VLC launches

### Additional context
VLC will launch from the terminal using flatpak run org.videolan.VLC

Related Issue: https://github.com/netblue30/firejail/issues/836

**Comment by Erick555** [comment]
> The issue is caused by firejail

If the issue us caused by firejail then why open it here?

**Comment by Tractor777** [comment]
I don't think it is caused by firejail. Sorry I missed the tick box config on the post.

**Comment by Tractor777** [comment]
Update - I had an instance of CVLC running in the background as an audio stream (I forgot it was using VLC) and if that is running then VLC will not launch even if "new window" is chosen frrom the right click on the menu icon. If no other instances of VLC or CVLC are running then VLC will launch from the icon.

**Comment by MatMaul** [comment]
Did you tick the option to only have one instance of VLC running by any chance?

**Comment by Tractor777** [comment]
ah, didn't know there was that setting. Yes I had "use only one instance when started from file manager" ticked ("Allow only one instance" was unticked). I have unticked that and it now opens VLC with the "--started-from-file" opption included. Thanks and closed/resolved
