### ISSUE TITLE
VLC does not show file dialog when try to open file or directory.

### ISSUE THREAD

**Issue by cathay4t** [flathub/org.videolan.VLC#45]
System is Centos 7.5.

Please let me if any log you required to investigate.

**Comment by eszlari** [comment]
What's you flatpak version? Qt based apps need at least 0.11.4 to make that work.

**Comment by cathay4t** [comment]
Aha. That's the problem. I got `flatpak-0.8.8-3.el7.x86_64`.
Closing this issue.
