### ISSUE TITLE
Fails to exit when UI is closed

### ISSUE THREAD

**Issue by hadess** [flathub/org.videolan.VLC#48]
I still have `vlc.bin` running even after closing VLC's main window. The application doesn't appear as running in gnome-shell.

I think the lack of `exec` before this line could be one of the causes:
https://github.com/flathub/org.videolan.VLC/blob/master/vlc.sh#L8

**Comment by hadess** [comment]
Even with the patch, this isn't actually fixed. Want me to create a new bug?

I think that it might have to do with the app using X11, and having a systray icon by default. The media player is "closed to the systray" when still playing back, but GNOME has nowhere to show that systray icon either. Maybe that should be disabled by default?

**Comment by MatMaul** [comment]
Then it's clearly not a bug, you would get the same with any packaged VLC. I don't really like the systray on default either but you'll have to see that with upstream.

**Comment by hadess** [comment]
> Then it's clearly not a bug, you would get the same with any packaged VLC. I don't really like the systray on default either but you'll have to see that with upstream.

Did you actually check that that's what it was doing, or did you just close the bug again based on my complete guesswork?

**Comment by MatMaul** [comment]
Check yourself by using a different DM that still supports systray ? I never had your problem to begin with, because I disable the systray option right away.

**Comment by hadess** [comment]
It would be great if you could close the bug when the bug is actually fixed :(

**Comment by MatMaul** [comment]
If it's what you just said, it is not a bug, and clearly not one in the packaging. If your guess is true you can take the default behavior discussion to VLC mailing. If not let's reopen, but your explanation seems quite plausible to me, and I can't test for you...

**Comment by hadess** [comment]
> and I can't test for you...

Is there no debug that I could gather for that purpose? Where does the code for the systray live in VLC, does it use Qt for that feature, and what happens when the the systray is not visible?

**Comment by MatMaul** [comment]
You can use `-vvv` in case you have some interesting logs but I am doubtful. To verify your theory the best is to just test in another DM.

Then for the rest I don't know right now, I can check the code. But again, it is still the wrong place :)
You should probably search https://trac.ffmpeg.org/ for similar issue, or open one.

**Comment by hadess** [comment]
After testing newer versions, the whole UI is incredibly broken when Qt reports that it doesn't support the systray (eg. that `QSystemTrayIcon::isSystemTrayAvailable()` returns false), as the main window can't be closed after it was "closed" once.

**Comment by hadess** [comment]
>  You should probably search https://trac.ffmpeg.org/ for similar issue, or open one.

Or rather: https://trac.videolan.org/vlc/
