### ISSUE TITLE
Flatpak RTSP fails to connect

### ISSUE THREAD

**Issue by wfrisby** [flathub/org.videolan.VLC#51]
Hello,

I'm running Fedora 28 silverblue with VLC inside a flatpack

Here is the flatpack info for org.videolan.VLC:
```
Ref: app/org.videolan.VLC/x86_64/stable
ID: org.videolan.VLC
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-11-08 14:42:39 +0000
Subject: Don't leave leftover shell process after executing vlc (ec83b849)
Commit: 9fafafb8dd66618a220bc8b345b704212a2425124e793661a180fe7f992d9177
Parent: 20914a5a1deb8e01be42747ca06bc3506c3f67a0f60840718877d72a160c5f30
Location: /var/lib/flatpak/app/org.videolan.VLC/x86_64/stable/9fafafb8dd66618a220bc8b345b704212a2425124e793661a180fe7f992d9177
Installed size: 79.2 MB
Runtime: org.kde.Platform/x86_64/5.11
Sdk: org.kde.Sdk/x86_64/5.11
```

However when I run VLC and connect to an RTSP stream it fails to establish a connection
`flatpak run org.videolan.VLC -vvv rtsp://192.168.0.113/stream1,audio=g711`

```
[00007f6388000980] main art finder debug: no art finder modules matched
[00007f638c001240] satip stream error: Failed to play RTSP session
[00007f638c001240] satip stream error: Failed to teardown RTSP session
[00007f638c001240] main stream debug: no access modules matched
[00000000021626e0] main playlist debug: dead input
[00000000021626e0] main playlist debug: changing item without a request (current 0/1)
[00000000021626e0] main playlist debug: nothing to play
[00000000021aa8c0] qt interface debug: IM: Deleting the input
```
The VLC about dialog message says that VLC is on 3.0.4 Vetinari, however with the same VLC version on another Fedora 28 machine (non-silverblue / project atomic/ no flatpack) viewing the RTSP stream works without any problem. The RTSP connection also work with openRTSP.

Any ideas?

**Comment by MatMaul** [comment]
Hum I don't know. Live555 is not on the deps but it looks like it is for serving only ?
And you seems to receive some log output from the RTSP reader.
Perhaps some network restriction ?

**Comment by MatMaul** [comment]
my bad, actually it's the other way around, live555 is used for client and custom vlc code for RTSP server. I'll try to add the dependency.

**Comment by MatMaul** [comment]
Tested with rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov and now working :)
