### ISSUE TITLE
cannot open VLC

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.videolan.VLC#54]
Hi
I use Arch Linux running flatpak 1.1.2, KDE Plasma 5.14.4 desktop environment.
"flatpak run app/org.videolan.VLC/x86_64/stable" command in terminal gives me the following error:
bwrap: Can't find source path /run/user/1000/doc/by-app/org.videolan.VLC: No such file or directory

**Comment by TingPing** [comment]
`xdg-document-portal` crashed or something.

**Comment by glaubersm** [comment]
in fact no flatpak is working on my system (discord, transmission, firefox, olive).
I always get the same error message in terminal.

**Comment by MatMaul** [comment]
closing then, please see with Arch flatpak maintainers.
