### ISSUE TITLE
Java support for blu-ray menus?

### ISSUE THREAD

**Issue by mr-falafel** [flathub/org.videolan.VLC#55]
I'm not sure whether this is a bug report or a feature request but blu-ray menus don't work for me. At least not the ones that require java, which is the large majority.

When loading a blu-ray disc (with java menus), I get this error:
"libbluray demux error: BD-J menus not supported. Playing without menus. BD-J support: 1, JVM found: 0, JVM usable: 0"

I have java installed on my system but I'm guessing that, being packaged as a flatpak, vlc wouldn't be able to see it anyway. Is there any possibility of fixing/adding support for java blu-ray menus?

*edited for clarity*

**Comment by MatMaul** [comment]
Work in progress ;)
It will be a separate flatpak package because it adds 100M to the app.
I'll also package libaacs/bdplus and I have a makemkv plugin working on top of that too.

**Comment by mr-falafel** [comment]
Wow! That's awesome to hear! I look forward to it! :) In the meantime, I'll mark this as closed. Thanks! :)

**Comment by jg-development** [comment]
Hi,
are there any updates on this issue?

**Comment by jg-development** [comment]
ahh I think it is this package?
org.videolan.VLC.Plugin.bdj

**Comment by happychameleon** [comment]
I have **org.videolan.VLC**, **org.videolan.VLC.Plugin.makemkv**, **org.videolan.VLC.Plugin.bdj**, yet I still get the error:
> libbluray demux error: BD-J menus not supported. Playing without menus. BD-J support: 1, JVM found: 1, JVM usable: 0
