### ISSUE TITLE
VLC does not start anymore

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.videolan.VLC#59]
After the latest update of VLC, it does not start anymore, giving instead the following error.

$ flatpak run org.videolan.VLC 
bwrap: Can't mkdir /usr/lib/sdk: Read-only file system

My system is Silverblue 29.20190104.0. I experienced the same error with MkvToolnix and suspect that it is related to the KDE 5.12 runtime, however I was unsure how to test or where to report.

**Comment by MatMaul** [comment]
Indeed nothing works anymore... It was working at some point, let's revert for now I'll setup a new develop branch for testing.

**Comment by mczimmermann** [comment]
Funny, I had just tested it on my other machine, same Silverblue version, KDE 5.12 runtime, and everything works fine. So I thought the error was not reproducible and was about to close the issue.

**Comment by MatMaul** [comment]
Should be solved once this is merged:
https://phabricator.kde.org/D18077

**Comment by MatMaul** [comment]
In the meantime you can just remove any 18.08 Sdk extension you have installed :)

**Comment by mczimmermann** [comment]
Everything works fine now, thank you very much!  As you pointed out, I guess it ran on my other machine because I had no instance of the 18.08 Sdk extension installed :)
