### ISSUE TITLE
icon disappears from systray on screen lock/unlock

### ISSUE THREAD

**Issue by freddyw** [flathub/org.videolan.VLC#66]
When using the 'show systray icon' and minimize to systray, the icon is gone after a screen lock/unlock. The app does continue playback. I cannot really see anything relevant in de journal logs.
I am using fedora 29 and up until recently it worked. Not quite sure when it stopped working. 
flatpak info org.videolan.VLC shows "Commit: fed20a3d952993357524a557a97cf4b81050848497c0fa824592dba6ac0abccc Date: 2019-02-06 15:08:04 +0000" as the version.

**Comment by freddyw** [comment]
I think the switch from runtime 5.11 to 5.12 was around the time the issue started appearing. Not really sure thouhg.

**Comment by MatMaul** [comment]
@freddyw Are you still having the issue ? What desktop do you use ? If gnome-shell, what extension for displaying the systray icons ?

**Comment by freddyw** [comment]
Yes, still having this issue. I am using gnome-shell (Fedora 30) and I have tried topicons-plus and I am currently using Unite. Both have this issue.

**Comment by MatMaul** [comment]
Please do a `flatpak update`, I think it just has been fixed wih Qt 5.12.4 :joy: 
I saw the update and did a before/after test and it did make it work for me.

**Comment by freddyw** [comment]
It indeed seems to be fixed with the latest flatpak versions.
