### ISSUE TITLE
vlc in flatpak completely hangs my pc

### ISSUE THREAD

**Issue by legacychimera247** [flathub/org.videolan.VLC#7]
everytime i play a file on my pc with vlc the computer completely freezes...seems that is related to vdpau drivers...while the rpm version tells me i don't have vdpau drivers and can't use them (then the file starts to play) the flatpak one just freezes my pc...maybe i need to install these drivers?

just in case i am using fedora 26 workstation...

unfortunately cmq seems the app freezes my pc this screen is the only info i can give you

https://1drv.ms/i/s!AlyMkCypv00qgsUIWmuNmM4UNwHFiw

**Comment by TingPing** [comment]
> maybe i need to install these drivers?

What GPU do you have?

At a glance Flatpak does ship `libva-vdpau-driver` for Intel users.

**Comment by legacychimera247** [comment]
my gpu is an ati radeon 4570 hd with 512 mb of memory...just a reminder that the rpm version works just fine (as every other player)

**Comment by MatMaul** [comment]
Please reopen if it's still the case, I think I know which bug it is (XWayland related) and it should be fixed.
