### ISSUE TITLE
main libvlc error: stale plugins cache: modified

### ISSUE THREAD

**Issue by Erick555** [flathub/org.videolan.VLC#77]
flatpak vlc app always prints below warnings at runtime. I cut the output for better readabilty:
```
$ flatpak run org.videolan.VLC
VLC media player 3.0.7.1 Vetinari (revision 3.0.7.1-0-gf3940db4af)
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/vaapi/libvaapi_filters_plugin.so
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/stream_out/libstream_out_delay_plugin.so
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/stream_out/libstream_out_cycle_plugin.so
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/stream_out/libstream_out_transcode_plugin.so
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/stream_out/libstream_out_standard_plugin.so
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/stream_out/libstream_out_autodel_plugin.so
[0000087a9d79c320] main libvlc error: stale plugins cache: modified /app/lib/vlc/plugins/stream_out/libstream_out_rtp_plugin.so
...
[0000087a9d79c320] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[0000087a9d7c96c0] main playlist: playlist is empty
```

**Comment by MatMaul** [comment]
Hum indeed. I solved that with https://github.com/flathub/org.videolan.VLC/blob/master/org.videolan.VLC.json#L58 a while ago, no idea why we have it back.

**Comment by Davo36** [comment]
I have come across this, this morning, should I raise a new issue?

I had trouble loading a video file.  I think that file is corrupt.  So I created the log and looked at it.  The first 50 lines or so are like this:

`main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libaccess_concat_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libaccess_imem_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libaccess_mms_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libaccess_realrtsp_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libaccess_srt_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libaccess_wasapi_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libattachment_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libcdda_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libdcp_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libdshow_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libdtv_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libdvdnav_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libdvdread_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libfilesystem_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libftp_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libhttps_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libhttp_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libidummy_plugin.dll
main error: stale plugins cache: modified D:\Program Files (x86)\VideoLAN\VLC\plugins\access\libimem_plugin.dll`

**Comment by leweex95** [comment]
I am facing the same trouble with the python-vlc package version 3.0.12118 on Windows 10. I see the above fix but I am unable to find which file I should modify to get it working (there's no `org.kde.elisa` file at `C:\Program Files (x86)\VideoLAN\VLC`).

**Comment by leweex95** [comment]
I am facing the same issue when using the `python-vlc` package version 3.0.12118 on Win10, and I'm not sure where the above mentioned fix should be applied exactly. Where can I find the `org.kde.elisa.json` file exactly?

**Comment by Erick555** [comment]
The patch is [here](https://github.com/flathub/org.videolan.VLC/blob/master/vlc-ignore-time-for-cache.patch). It's the vlc that needs to be patched and recompiled. I have no idea if it can fix your issue on windows.

**Comment by merrychrishna** [comment]
why is the patch not in 3.0.16 64bit for windows? im still getting the stale plugin errors.

**Comment by Erick555** [comment]
I recommend to report this issue [here](https://code.videolan.org/videolan/vlc/-/issues/) because this one is strictly for linux and flatpak. You may mention patch listed above.

**Comment by TrickQuestion** [comment]
I have this problem occurring for a small mp3 file I generated. It's only a problem for that file. Other files I generate work well in VLC, and I've never had another issue. The logfile lists every single dll in the VLC directory tree. No idea what's doing this but I will experiment by creating different mp3 files to see if I can isolate the issue.

**Comment by jasells** [comment]
I see the same errors on windows if I run from the .jar package I made to deploy with a java app I'm working on.  Might it be looking in registry for the path from installer?  When I run the .msi installer the problem goes away, even if I uninstall.  Maybe would come back after a restart and registry is cleaned up?

**Comment by ClaireCJS** [comment]
* if you see a bunch of ```stale plugins cache``` errors, you can fix with ```"C:\Program Files\VideoLAN\VLC\vlc-cache-gen.exe" "C:\Program Files\VideoLAN\VLC\plugins"``` (found the [answer here](https://stackoverflow.com/questions/68246840/how-to-avoid-main-libvlc-error-when-using-the-python-vlc-package)])

**Comment by gtkpr** [comment]
Didn't work for me. Specific media file is still throwing these errors in the log
