### ISSUE TITLE
VLC can't play from external hard drive

### ISSUE THREAD

**Issue by alexandrevicenzi** [flathub/org.videolan.VLC#8]
VLC only works if the video is from `/home`.

I have multiple hard drives on my PC, and I cannot play from the others HDDs or from any USB HDD.

This is what I get:

```
File reading failed:
VLC could not open the file "/run/media/alexandre/f14881f5-2376-4efc-b4df-b1a44a5f12a4/video.mp4" (No such file or directory).
Your input can't be opened:
VLC is unable to open the MRL 'file:///run/media/alexandre/f14881f5-2376-4efc-b4df-b1a44a5f12a4/video.mp4'. Check the log for details.
```

If I click on "Media > Open File" go to "Other Locations" it doesn't show any mounted HDD, except the drive from the OS.

I'm using OpenSUSE Leap 42.3 with Gnome.

**Comment by wanshanchen** [comment]
This is closed, but the issued is not solved

**Comment by lunanigra** [comment]
Having the same issue using Ubuntu 17.10.
Path is /media/[username]/[something]

When trying to open a file via VLC the /media folder is totally empty - so nothing to select.

**Comment by MatMaul** [comment]
This is probably related to Flatpak integration in Ubuntu, it works fine on Fedora. Probably a missing or wrong AppArmor policy.
You can try with a more recent Flatpak version from this PPA:
https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak/
and/or try with Ubuntu 18.04.

Anyway please report your findings here:
https://bugs.launchpad.net/ubuntu/+source/flatpak

**Comment by MatMaul** [comment]
And let's see if @alexlarsson has something to say on that ;)

**Comment by MatMaul** [comment]
Ok so I just see that OpenSUSE is also having the problem (1st post) so I am pretty sure it is AppArmor related.

**Comment by marcosps** [comment]
@alexandrevicenzi @MatMaul I think this is done on purpose. Flatpak also does not symlink directories, avoiding the VLC (in this case) to access files that are not in the user's HOME directory, going through the system directories... I think that /media is not mapped to the default directories to be opened by flatpak. Or maybe the files inside /media are symlinks, so they are not being shown by VLC.

@TingPing @alexlarsson is this right or am I missing something?

**Comment by MatMaul** [comment]
I am closing for now.
