### ISSUE TITLE
VLC is not showing up at App Center

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.videolan.VLC#81]
![Captura de tela de 2019-06-20 19-08-19](https://user-images.githubusercontent.com/26097419/59884525-054c3e80-938f-11e9-9d93-de9bb494869e.png)

**Comment by MatMaul** [comment]
Indeed, thanks. The way it works changed recently for that I think, I have to do some work on the appdata so we get it back.

**Comment by LeandroStanger** [comment]
![Captura de tela de 2019-06-25 08-35-31](https://user-images.githubusercontent.com/26097419/60095116-3b3d4a00-9724-11e9-873a-383f949c6c01.png)
