### ISSUE TITLE
Cannot load .ass subtitles file located on a samba share

### ISSUE THREAD

**Issue by geext-dk** [flathub/org.videolan.VLC#88]
When I open a video with an .ass file placed with it (with the same name) both located on a samba share, the subtitle file  will not get autoloaded when opening the video. The video works fine. Moreover, if I try to add the subtitle track manually (Right click -> subtitles -> Add Subtitle File...) VLC will just hang. Then I can only kill it and nothing else.

**Comment by MatMaul** [comment]
This should have been solved a while ago by #86 for Gnome. For KDE I don't know.
What's your distro and desktop environment ?

**Comment by geext-dk** [comment]
You're right. I just checked it on GNOME and it worked. Looks like it doesn't work on KDE though.

**Comment by geext-dk** [comment]
On a fully updated KDE Neon with flatpak from ppa automatic loading of subtitles doesn't work, but it works if they are loaded through the context menu.

**Comment by MatMaul** [comment]
Ok I had a quick look at the time when I fixed it for Gnome and couldn't get how exactly KDE handles Samba shares. I don't have time right now but if you manage to get more infos on that (is it mounted somewhere and where ?) I can probably help.
If it's not mounted and they stream it directly through a library with a "fake" file I can't do much I am afraid...

**Comment by MatMaul** [comment]
Last but not least: do you have the problem with VLC coming from apt (not the Snap version) ?

**Comment by geext-dk** [comment]
Okay it doesn't work with VLC from the ubuntu repositories too. Looks like it's KDE feature. Unlike GTK file dialogs (or Nautilus), KDE file dialogs (or Dolphin) don't mount samba shares when accessing it, so it passes smb:// links to VLC and VLC can't look up subtitles in a remote directory. (P. S. VLC from snap store in this case first downloads the video file before opening it, amazing). But when mounted dolphin will pass ordinary file:// links to VLC so it will try look up the subtitles file and it therefore works.

Closing since it's a KDE feature (arguably). The workaround is to mount the samba share manually.

**Comment by MatMaul** [comment]
Thanks for the investigation. Perhaps worth opening a bug on the VLC tracker, because on the principle if the SMB link is passed directly it's probably doable to handle that in VLC SMB code.
