### ISSUE TITLE
Blu-ray can not be played (with Plugin.makemkv and Plugin.bdj)

### ISSUE THREAD

**Issue by happychameleon** [flathub/org.videolan.VLC#91]
I have installed the org.videolan.VLC.Plugin.makemkv and org.videolan.VLC.Plugin.bdj plugins,
but vlc fails to play my Blu-ray (the Blu-ray was playable in the past), I have the impression that vlc is unable to use the installed plugins but don't know why that is.
when starting vlc in the commandline with `flatpak run org.videolan.VLC` I get the following output:

> VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[0000562fa4dd9080] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Gtk-Message: 17:04:36.083: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:04:36.084: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[0000562fa4e70f70] main playlist: playlist is empty
aacs.c:121: No usable AACS libraries found!
dec.c:197: aacs_open() failed: -1!
[00007fefb8001120] libbluray demux: First play: 1, Top menu: 1
HDMV Titles: 2, BD-J Titles: 79, Other: 0

**Comment by MatMaul** [comment]
Have you put the MakeMKV license key in place ?

**Comment by MatMaul** [comment]
Also can you do a `flatpak list` and reports the branches of the plugins and VLC ?

**Comment by happychameleon** [comment]
> Have you put the MakeMKV license key in place ?

yep that was the issue thanks, i did not have the problem last time because i had installed the makemkv beta software before i installed the plugin for vlc
