### ISSUE TITLE
Use the FFmpeg runtime

### ISSUE THREAD

**Issue by ricvelozo** [flathub/org.videolan.VLC#94]
Use the FFmpeg runtime like [org.blender.Blender](https://github.com/flathub/org.blender.Blender/pull/43).

**Comment by Erick555** [comment]
The `org.freedesktop.Platform.ffmpeg-full` extension is still quite far from being _full_ and I wouldn't recommend it without careful testing for regressions. In vlc case which really wants full _ffmpeg_ this may be hopeless.

**Comment by MatMaul** [comment]
Indeed as mentioned full is not full at all :)
