### ISSUE TITLE
Improve screenshots in appdata

### ISSUE THREAD

**Issue by TingPing** [flathub/org.videolan.VLC#98]
They are all bad, incorrectly sized, show the desktop...

**Comment by MatMaul** [comment]
It seems to work fine for me now, at least on Wayland and GL output.

**Comment by TingPing** [comment]
I think you are talking about something else. These need to be re-done: https://github.com/flathub/org.videolan.VLC/blob/99f588f67b460b1ab4d4a05368e7ebe7ba4a5754/org.videolan.VLC.appdata.xml#L48-L50

**Comment by MatMaul** [comment]
Ah right ! this should be a bit better:
https://github.com/flathub/org.videolan.VLC/pull/134

**Comment by TingPing** [comment]
Its a slight improvement. The screenshot should just be of the window though and not a desktop. I think somebody needs to make new ones by hand rather than relying on upstreams examples.

**Comment by MatMaul** [comment]
I can take screenshots but the main problem is hosting them. Do you have access to some static hosting on flathub.org that could be used for that ?

**Comment by MatMaul** [comment]
Or can it be just embedded in the repo and referenced ?

**Comment by TingPing** [comment]
You should just put them in this repo.

**Comment by MatMaul** [comment]
Well I can at least reference a GitHub asset. Let me know what is the preferred way.

**Comment by MatMaul** [comment]
I have updated the PR with a couple of fresh made screenshots, let me know if they look ok to you @TingPing .
