### ISSUE TITLE
(VLC-Flatpak) VLC doesn't start as long as Xwayland is not running

### ISSUE THREAD

**Issue by antistress** [flathub/org.videolan.VLC#99]
Hi,

Here is a always reproductible one that I've found :

On my Debian Sid GNOME-Wayland system, I've started to try the experimental function from GNOME 3.34 (I'm running GNOME 3.34.2) that allows Xwayland to start on demand :
$ gsettings set org.gnome.mutter experimental-features "['autostart-xwayland']"
(see https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.34-Mutter-X-On-Demand)

Here what I've noticed :
- As long as XWayland is not running, VLC-Flatpak doesn't start.
- As soon as XWayland is running, VLC-Flatpak can be started.
- Launch VLC-Flatpak and then later start XWayland : VLC-Flatpak finally appears on my desktop.

By comparison, VLC deb package from Debian repos can start without Xwayland.

How I've tested :
I've checked that my system starts without Xwayland by checking my processes
To start Xwayland, I've launched an X11-application (like Thunderbird or Firefox from Debian repos) which consequently starts Xwayland which consequently allow VLC-Flatpak to start.
I've checked that Xwayland was running by checking my processes.

Note that LibreOffice-Flatpak suffers from the same bug : https://bugs.documentfoundation.org/show_bug.cgi?id=131623

I'm running VLC-Flatpak up to date from FlatHub : 
Version 3.0.8 buildbot@cncf-x86-2.flathub.org Feb 26 2020 00:20:31

Thanks

**Comment by Erick555** [comment]
If the goal here is to run vlc on wayland natively then you may try adding wayland permission like `flatpak run --socket=wayland org.videolan.VLC`. This assumes vlc has native wayland support otherwise there is nothing you can do.

**Comment by antistress** [comment]
> If the goal here is to run vlc on wayland natively then you may try adding wayland permission like `flatpak run --socket=wayland org.videolan.VLC`. This assumes vlc has native wayland support otherwise there is nothing you can do.
Actually it doesn't solve the problem :
Keying `flatpak run --socket=wayland org.videolan.VLC` lead to the same situation : VLC-Flatpak wait Xwayland to launch itself. Once XWayland is started, VLC-Flatpak appears
In terminal it means that :
`$ flatpak run --socket=wayland org.videolan.VLC
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)`
until I start Xwayland, then I get :
`[000055eec084c6a0] main libvlc: Lancement de vlc avec l'interface par défaut. Utiliser « cvlc » pour démarrer VLC sans interface.
Qt: Session management error: None of the authentication protocols specified are supported
[000055eec08e4e60] main playlist: playlist is empty` 
while the VLC GUI shows itself
Thanks

Note that other application-Flatpak suffers from the same bug : FileZilla, Audacity, Avidemux, Calibre, Frozen Bubble, GIMP.
Whereas Shotwell, Pitivi and Transmission don't suffer from this bug.

**Comment by Erick555** [comment]
> Note that other application-Flatpak suffer from the same bug : FileZilla, Audacity, Avidemux, Calibre, Frozen Bubble, GIMP, Thunderbird.
> Whereas Shotwell, Pitivi and Transmission don't suffer from this bug.

I guess apps that work use native wayland instead of xwayland. It's possible that flatpak doesn't support xwayland on-demand but you may ask here to confirm: https://github.com/flatpak/flatpak/issues . Anyway if it affects so many apps then it's a generic flatpak issue and app developers won't help you.

**Comment by antistress** [comment]
Thanks
See https://github.com/flatpak/flatpak/issues/3509

**Comment by MatMaul** [comment]
I am closing this one since it is clearly an upstream(s) bug(s), thanks for the detailed report anyways :)
